version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host
    environment:
      - NODE_ENV=development

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Rent_database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../backend/Rent_database_updated.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: